#!/bin/bash

# Daily Tech Company Research Tracker
# Usage: ./tech_research_tracker.sh [date]

DATE=${1:-$(date +%Y-%m-%d)}
OUTPUT_FILE="tech_company_${DATE}.md"

# Companies and their research URLs
declare -A COMPANIES=(
    ["Google DeepMind"]="https://deepmind.google/research/publications"
    ["OpenAI"]="https://openai.com/research"
    ["Meta FAIR"]="https://ai.meta.com/research/"
    ["Anthropic"]="https://www.anthropic.com/research"
    ["NVIDIA"]="https://research.nvidia.com/publications"
    ["Tesla"]="https://tesla.com/ai"
    ["Apple"]="https://www.apple.com/research/"
    ["Microsoft Research"]="https://www.microsoft.com/en-us/research/"
)

# Create header
cat > "${OUTPUT_FILE}" << EOF
# Daily Tech Company Research Tracker
**Date**: ${DATE}
**Timestamp**: $(date -u +"%Y-%m-%d %H:%M UTC")
**Status**: Running

## Research Summary
Automated research tracking of leading tech companies' latest publications and updates.

## Companies Tracked
EOF

# Process each company
for company in "${!COMPANIES[@]}"; do
    echo "Processing $company..."
    
    # Try defuddle.md first
    defuddle_url="https://defuddle.md/${COMPANIES[$company]}"
    response=$(curl -s -o /dev/null -w "%{http_code}" "$defuddle_url" 2>/dev/null)
    
    if [ "$response" = "200" ]; then
        echo "| ✅ | defuddle.md | ${COMPANIES[$company]} |" >> "${OUTPUT_FILE}"
        curl -s "$defuddle_url" >> "${OUTPUT_FILE}"
    else
        # Try r.jina.ai as fallback
        jina_url="https://r.jina.ai/${COMPANIES[$company]}"
        response=$(curl -s -o /dev/null -w "%{http_code}" "$jina_url" 2>/dev/null)
        
        if [ "$response" = "200" ]; then
            echo "| ✅ | r.jina.ai | ${COMPANIES[$company]} |" >> "${OUTPUT_FILE}"
            curl -s "$jina_url" >> "${OUTPUT_FILE}"
        else
            # Mark as failed
            echo "| ❌ | Network/Timeout | ${COMPANIES[$company]} |" >> "${OUTPUT_FILE}"
        fi
    fi
    
    echo "" >> "${OUTPUT_FILE}"
done

# Add footer
cat >> "${OUTPUT_FILE}" << EOF

---
*Generated by Daily Tech Company Research Tracker*
*Run time: $(date)*
EOF

echo "Research tracker completed: ${OUTPUT_FILE}"